import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import "@mantine/core/styles.css";
import '@mantine/dates/styles.css';
import { MantineProvider } from "@mantine/core";
import "./globals.css";
import clsx from "clsx";
import localFont from "next/font/local";

import { NextIntlClientProvider, useMessages } from "next-intl";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ibm = localFont({
  src: [
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf",
      weight: "100",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf",
      weight: "200",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf",
      weight: "300",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-ibm",
});

export default function RootLayout({ children , params}) {
  const messages = useMessages();
  return (
    <html lang={params.locale} dir={params.locale === "ar" ? "rtl" : "ltr"}>
      <body className={clsx(ibm.variable, "text-black")}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <MantineProvider theme={"light"}>{children}</MantineProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
