<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\AppResults\**" />
    <Compile Remove="Constants\Policies\**" />
    <EmbeddedResource Remove="Common\AppResults\**" />
    <EmbeddedResource Remove="Constants\Policies\**" />
    <None Remove="Common\AppResults\**" />
    <None Remove="Constants\Policies\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
  </ItemGroup>

</Project>
