import "./globals.css";
import clsx from "clsx";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ibm = localFont({
  src: [
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf",
      weight: "100",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf",
      weight: "200",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf",
      weight: "500",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-ibm",
});

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={clsx(ibm.variable, "text-black")}>{children}</body>
    </html>
  );
}
