<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <PreserveCompilationContext>true</PreserveCompilationContext>
    <DocumentationFile>..\Spectra.WebAPI\SpectraApiDocs.xml</DocumentationFile>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="ClientApp\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="wwwroot\Documents\**" />
    <Content Remove="ClientApp\**" />
    <Content Remove="Services\**" />
    <Content Remove="wwwroot\Documents\**" />
    <EmbeddedResource Remove="ClientApp\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="wwwroot\Documents\**" />
    <None Remove="ClientApp\**" />
    <None Remove="Services\**" />
    <None Remove="wwwroot\Documents\**" />
  </ItemGroup>


  <ItemGroup>
    <None Remove="libwkhtmltox.dll" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="libwkhtmltox.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.1.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="1.2.49" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spectra.WebAPI\Spectra.WebAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
